[package]
name = "orma"
version = "0.1.0"
authors = ["Andrea Chiumenti <achiumenti@red.software.systems>"]
edition = "2018"
license = "MIT"
description = "A PostgreSQL ORM wirtten in Rust language"
repository = "https://github.com/RedSoftwareSystems/rust-orma"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "orm", "orma", "jsonb", "json"]
categories = ["database"]

[dependencies]
tokio-postgres = {version = "0.5.1", features = ["with-uuid-0_8", "with-serde_json-1", "runtime"]}
serde = {version = "1.0.104", features = [ "derive" ]}
serde_json = "1.0.44"
serde_derive = "1.0.104"
futures = "0.3.1"
tokio = { version = "0.2.9", features = [ "full" ] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }