[package]
name = "orma"
version = "0.1.4"
authors = ["Andrea Chiumenti <achiumenti@red.software.systems>"]
edition = "2018"
license = "MIT"
description = "A PostgreSQL ORM written in Rust language"
repository = "https://github.com/RedSoftwareSystems/rust-orma"
readme = "../README.md"
keywords = ["postgres", "postgresql", "orm", "sql", "json"]
categories = ["database"]

[dependencies]
tokio-postgres = {version = "0.5.1", features = ["with-uuid-0_8", "with-serde_json-1", "runtime"]}
serde = {version = "1.0.104", features = [ "derive" ]}
serde_json = "1.0.45"
serde_derive = "1.0.104"
futures = "0.3.1"
tokio = { version = "0.2.11", features = [ "full" ] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
orma-derive = { version = "=0.1.4", optional = true, path = "../orma-derive" }


[dev-dependencies]
orma-derive = { version = "=0.1.4", path = "../orma-derive" }

### FEATURES #################################################################

[features]
# Provide derive(Serialize, Deserialize) macros.
derive = ["orma-derive"]